[project]
name = "vllm-lmcache"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "datasets>=2.14.0",
    "openai>=1.0.0",
]
